# Generated by Django 5.2 on 2025-04-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image_url", models.URLField()),
                ("synopsis", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("cast", models.TextField()),
                ("predicted_attendance", models.IntegerField()),
                ("room", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_attendance", models.IntegerField()),
                ("actual_attendance", models.IntegerField()),
                ("date", models.DateField()),
                ("accuracy", models.FloatField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="films.movie"
                    ),
                ),
            ],
        ),
    ]
