# Generated by Django 5.2 on 2025-04-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('release_date_fr', models.DateField(default=None, null=True)),
                ('first_week_actual_entries_france', models.IntegerField(default=None, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_week_predicted_entries_france', models.IntegerField(default=0)),
                ('prediction_error', models.IntegerField(default=0)),
                ('model_version', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='films.movie')),
            ],
        ),
    ]
