# Generated by Django 5.2 on 2025-04-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='predicted_attendance',
            new_name='actual_entries_france',
        ),
        migrations.RenameField(
            model_name='predictionhistory',
            old_name='actual_attendance',
            new_name='first_week_predicted_entries_france',
        ),
        migrations.RenameField(
            model_name='predictionhistory',
            old_name='accuracy',
            new_name='metric_score',
        ),
        migrations.RenameField(
            model_name='predictionhistory',
            old_name='predicted_attendance',
            new_name='model_version',
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='films.movie'),
        ),
    ]
