# Generated by Django 5.2 on 2025-04-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='predicted_attendance',
            new_name='actual_entries_france',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='actual_attendance',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='predicted_attendance',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date_fr',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='first_week_predicted_entries_france',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='model_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='prediction_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='films.movie'),
        ),
    ]
