# Generated by Django 5.2 on 2025-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='first_week_actual_entries_france',
            field=models.IntegerField(default=0),
        ),
    ]
