# Generated by Django 5.2 on 2025-04-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_movie_first_week_actual_entries_france'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room_1', models.IntegerField(blank=True, null=True)),
                ('room_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='room',
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('room_1_predicted', models.FloatField(default=0.0)),
                ('room_1_actual', models.IntegerField(default=0)),
                ('room_1_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('room_2_predicted', models.FloatField(default=0.0)),
                ('room_2_actual', models.IntegerField(default=0)),
                ('room_2_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consumptions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('room_1_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_1', to='films.movie')),
                ('room_2_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_2', to='films.movie')),
            ],
        ),
    ]
