# Generated by Django 5.2 on 2025-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_boadcast_broadcast_recette_broadcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='broadcast',
        ),
        migrations.AddField(
            model_name='recette',
            name='broadcast_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
